# Generated by Django 5.2.4 on 2026-04-16 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0013_expopushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Notification title e.g. 'Happy Vishu 🎉'", max_length=255)),
                ('body', models.TextField(help_text='Notification body message')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL to show in notification', null=True)),
                ('target', models.CharField(choices=[('all', 'All Users'), ('active', 'Active Users Only')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Leave blank to send immediately', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0, help_text='Number of tokens notified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Common Notification',
                'verbose_name_plural': 'Common Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
