# Generated by Django 5.2.4 on 2026-04-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0014_commonnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonnotification',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file (JPG/PNG/WebP, max 5 MB)', null=True, upload_to='notification_images/'),
        ),
        migrations.AlterField(
            model_name='commonnotification',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional image URL to show in notification (used when no file is uploaded)', null=True),
        ),
    ]
