# Generated by Django 5.2.4 on 2026-04-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0015_commonnotification_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expopushtoken',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM token — used only for CommonNotification', max_length=512, null=True),
        ),
    ]
