# Generated by Django 5.2.4 on 2026-04-25 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0016_expopushtoken_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional label for this PDF', max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(help_text='Public R2 URL of the uploaded PDF', max_length=1000)),
                ('file_key', models.CharField(help_text='R2 object key (path inside bucket)', max_length=500)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Invoice',
                'verbose_name_plural': 'PDF Invoices',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
