# Generated by Django 5.2.4 on 2026-05-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0017_pdfinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='expopushtoken',
            name='apns_device_token',
            field=models.CharField(blank=True, help_text='Raw APNs device token — used for iOS image notifications', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expopushtoken',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='FCM token — used only for CommonNotification (Android)', max_length=512, null=True),
        ),
    ]
