# Generated by Django 5.2.4 on 2026-05-04 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0018_expopushtoken_apns_device_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional label shown in admin panel', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Banner image (JPG/PNG/WebP, max 5 MB)', upload_to='banner_images/')),
                ('link_url', models.URLField(blank=True, help_text='Optional deep-link or web URL when banner is tapped', max_length=1000, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order — lower number appears first')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
