# Generated by Django 5.2.4 on 2026-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0019_bannerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerimage',
            name='status',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(upload_to='banner_images/'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='link_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
