# Generated by Django 5.2.4 on 2026-05-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0020_remove_bannerimage_status_bannerimage_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Unused — banners are only deleted when admin deletes them manually.', null=True),
        ),
    ]